name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your branch name

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # deploy from root, where all folders are

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
